name: assignment_app
description: "Flutter developer assignment — users, movies, offline sync, WorkManager."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  drift: ^2.22.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.28
  path: ^1.9.0
  path_provider: ^2.1.5
  workmanager: ^0.5.2
  connectivity_plus: ^6.1.1
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
